baseurl = "https://shubhamutwal.in"
languageCode = "en-us"
title = "Shubham Utwal"
theme = "hermit"
copyright = "&copy; <a href=\"https://shubhamutwal.in\">Shubham Utwal</a> 2021"
disqusShortname = "shubhamutwal"
googleAnalytics = "UA-132832700-1"
rssLimit = 10
pygmentsCodefences  = true
pygmentsUseClasses  = true
favicon = "favicon.ico"
enableEmoji = true

[author]
  name = "Shubham Utwal"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = ""  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  
  homeSubtitle = "Payments | Distributed Systems | Data"

  [params.highlight]
  style = "github"
  languages = ["go", "dockerfile"]

  # Social Icons
  [[params.social]]
  url = "https://github.com/darkdefender27"
  name = "github"

  [[params.social]]
  url = "https://instagram.com/_b.mag/"
  name = "instagram"

  [[params.social]]
  url = "https://in.linkedin.com/in/shubhamutwal"
  name = "linkedin"

  [[params.social]]
  url = "https://www.facebook.com/shubhamutwal"
  name = "facebook"

  [[params.social]]
  url = "mailto:shubhamutwal@gmail.com"
  name = "email"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
